package io.dongxi.model

import kotlinx.serialization.Serializable


/**
 * A CPF is a Cadastro de Pessoa Física, an 11-digit number in the format 000.000.000-00
 *
 * The first eight digits are the base.
 * The ninth digit indicates the fiscal region in Brasil.  (If 10, uses 0.)
 * The last two digits are check digits, generated by a hash of the first nine digits.
 */
@Serializable
data class CPF(
    val first3Digits: Int,
    val second3Digits: Int,
    val third3Digits: Int,
    val checkDigits: Int
) {

    private var errorMessage: String? = null

    fun isValid(): Boolean {
        // TODO Check for required character mix.
        return true
    }

    fun getErrorMessage(): String {
        return errorMessage ?: ""
    }

    override fun toString(): String {
        return "$first3Digits.$second3Digits.$third3Digits-$checkDigits"
    }
}